name: Metrics

on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: svqzd
          template: classic
          base: header, activity, community, metadata
          config_timezone: Europe/Bucharest
          config_twemoji: yes
          config_gemoji: no
          plugin_habits: yes
          plugin_habits_days: 7
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages-graphs, os-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_languages_other: yes
          repositories_affiliations: owner, collaborator
